### ISSUE TITLE
I want to use picture element with webp and jpeg sources

### ISSUE THREAD

**Issue by navanshu** [dombrant/blurry-image-load#1]
I want first to show a small blurry image to users and after all scripts are loaded magically reveal all the images using intersection observer.
```javascript
<picture>
    <source type="image/webp"
            srcset="images/worlds-300.webp 300w,
                    images/worlds-600.webp 600w,
                    images/worlds-800.webp 800w,
                    images/worlds.webp 1000w"
             />
    <source srcset="images/worlds-300.jpg 300w,
                    images/worlds-600.jpg 600w,
                    images/worlds-800.jpg 800w,
                    images/worlds.jpg 1000w"
            />
    <img src="images/worlds-300.jpg"
    alt="The Speed of Light and the Timing of Eclipses" />
  </picture>
```
How can I do this or modify your script to achieve it. Since the present implimentation limits my case.

**Comment by dombrant** [comment]
First off, thanks for using my library! Second, I just edited my demo page to include an example with the picture element (with source elements of both .webp and .jpg images like your example). It appears to work for me in Chrome, Firefox, and Safari.

As far as using the library with IntersectionObserver, I recently added that functionality! Starting with version 3.0 (commit 61ab96dc78165ff3c9d85b5d3c7d8ca5a7d18020), you can create an instance of the `BlurryImageLoad` class, and call the `load()` function, passing in an array of the element(s) to load. See the [Usage section of the README](https://github.com/dombrant/blurry-image-load#usage) for more info. Perhaps you're using version 2.x?

I hope this helps, if not feel free to reply. I'll leave this issue open for a little while.

**Comment by dombrant** [comment]
I'm gonna close this issue due to inactivity. Feel free to reach out if you still have any questions.
